/***
 *  地图瓦片枚举
 * */
export enum TILE_TYPE_ENUM {
  WALL_ROW = 'WALL_ROW',
  WALL_COLUMN = 'WALL_COLUMN',
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  CLIFF_LEFT = 'CLIFF_ROW_START',
  CLIFF_CENTER = 'CLIFF_ROW_CENTER',
  CLIFF_RIGHT = 'CLIFF_ROW_END',
  FLOOR = 'FLOOR',
}